"""Update 'tasks' table

Revision ID: 13ec14afad28
Revises: f4e905e70029
Create Date: 2022-02-11 16:05:17.205108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ec14afad28'
down_revision = 'f4e905e70029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_log', 'start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('time_log', 'end',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_log', 'end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('time_log', 'start',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
