"""add auth

Revision ID: 3d7978de09c4
Revises: 2ccef6efa030
Create Date: 2022-09-09 15:02:18.618553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7978de09c4'
down_revision = '2ccef6efa030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
